### ISSUE TITLE
フロントエンド(Angular)のモジュール化について

### ISSUE THREAD

**Issue by chameleonhead** [itplanco/weekly_reports#1]
現在、ページごとに分かれているモジュールの分け方について再度検討しておきたい。

案：関連するコンポーネント同士は同一のフォルダに分割して配置する。
フォルダーの分割単位を以下のように考える。

- /: Appモジュール(モジュール化しないもの・ログインせずに使用可能なもの等)
    - /login: ログイン画面のコンポーネント・認証のサービス等を配置する
    - /common: 共通モジュール(今回作成する以下のモジュールに含まれないコンポーネント・ディレクティブ等)を配置する
- /admin: 管理モジュール(ユーザー管理・マスタ管理等)
- /reports: 週報モジュール(週報の入力・編集等)

**Comment by kkawaguchi** [comment]
わかりました。
