### ISSUE TITLE
ReportクラスのdataとRequestクラスのparamについて

### ISSUE THREAD

**Issue by match5121** [itplanco/weekly_reports#2]
RequestのparamはRouteのparamに'data'というキーで格納されるようですが、
Reportのdataに対応する値はRouteのparam['data']['data']に格納される仕様でしょうか。

RouteのexecuteControllerActionメソッドの実装が誤っているのか各クラスで整合性が取れていないように見えます。前述の仕様と判断しましたがイマイチ自信がありません。

**Comment by match5121** [comment]
ごめんなさい、勘違いでした。pathMatchが読めてませんでした。
閉じます。

**Comment by chameleonhead** [comment]
$request->dataはput/postの際のリクエストボディが入るイメージで、実装は単に$_POSTを入れ替えているだけです。なので、その認識で問題無いと思います。
不具合があれば修正して貰っても大丈夫です。

**Comment by match5121** [comment]
確認ですが、
例えば、requestのurlが _api/reports/2016/1/1_ で、
ルーティングされたコントローラのキーが _api/reports/:year/:weeknum/:id_ 、
リクエストボディに key "Jisseki" 、value "AAA" が格納されていたとき、
paramは次のようになる認識でよいでしょうか。

'param' => Array (
　　'year' => '2016',
　　 'weeknum' => '1',
　　 'id' => '1',
　　 'data' => Array(
　　　　'Jisseki' => 'AAA'
　　)
)

**Comment by chameleonhead** [comment]
そうなるはずだと思います。
