### ISSUE TITLE
Reportのparseを削除

### ISSUE THREAD

**Issue by match5121** [itplanco/weekly_reports#3]
parseはReportクラスではなく、ReportsApiControllerクラスの責務と考え、
Reportクラスからparseメソッドを削除しました。

ReportsApiControllerクラスでデータフォーマットの変換を行ってよいでしょうか。
データフォーマットの変換はcontrollerかrepositoryのどちらかで行うこととしたいです。

**Comment by chameleonhead** [comment]
Model::parseメソッドについてデータの変換というよりはデシリアライズなのでController/Repositoryには入れたくないと思っています。
というのは配列→オブジェクトの変換についてはフレームワークの一部と考えているためです。
Modelに持たないのであればそのロジックを入れる場所を新たに考える必要があります。

新たにクラスを作成するべきでしょうか。
